/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SiteRouteImport } from './routes/_site'
import { Route as SiteIndexRouteImport } from './routes/_site.index'
import { Route as SiteWorkRouteImport } from './routes/_site.work'
import { Route as SiteResumeRouteImport } from './routes/_site.resume'
import { Route as SiteContactRouteImport } from './routes/_site.contact'
import { Route as SiteProjectsSlugRouteImport } from './routes/_site.projects.$slug'

const SiteRoute = SiteRouteImport.update({
  id: '/_site',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteIndexRoute = SiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteWorkRoute = SiteWorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => SiteRoute,
} as any)
const SiteResumeRoute = SiteResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => SiteRoute,
} as any)
const SiteContactRoute = SiteContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => SiteRoute,
} as any)
const SiteProjectsSlugRoute = SiteProjectsSlugRouteImport.update({
  id: '/projects/$slug',
  path: '/projects/$slug',
  getParentRoute: () => SiteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof SiteIndexRoute
  '/contact': typeof SiteContactRoute
  '/resume': typeof SiteResumeRoute
  '/work': typeof SiteWorkRoute
  '/projects/$slug': typeof SiteProjectsSlugRoute
}
export interface FileRoutesByTo {
  '/contact': typeof SiteContactRoute
  '/resume': typeof SiteResumeRoute
  '/work': typeof SiteWorkRoute
  '/': typeof SiteIndexRoute
  '/projects/$slug': typeof SiteProjectsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_site': typeof SiteRouteWithChildren
  '/_site/contact': typeof SiteContactRoute
  '/_site/resume': typeof SiteResumeRoute
  '/_site/work': typeof SiteWorkRoute
  '/_site/': typeof SiteIndexRoute
  '/_site/projects/$slug': typeof SiteProjectsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/contact' | '/resume' | '/work' | '/projects/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/contact' | '/resume' | '/work' | '/' | '/projects/$slug'
  id:
    | '__root__'
    | '/_site'
    | '/_site/contact'
    | '/_site/resume'
    | '/_site/work'
    | '/_site/'
    | '/_site/projects/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SiteRoute: typeof SiteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_site': {
      id: '/_site'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site/': {
      id: '/_site/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SiteIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/work': {
      id: '/_site/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof SiteWorkRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/resume': {
      id: '/_site/resume'
      path: '/resume'
      fullPath: '/resume'
      preLoaderRoute: typeof SiteResumeRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/contact': {
      id: '/_site/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof SiteContactRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/projects/$slug': {
      id: '/_site/projects/$slug'
      path: '/projects/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof SiteProjectsSlugRouteImport
      parentRoute: typeof SiteRoute
    }
  }
}

interface SiteRouteChildren {
  SiteContactRoute: typeof SiteContactRoute
  SiteResumeRoute: typeof SiteResumeRoute
  SiteWorkRoute: typeof SiteWorkRoute
  SiteIndexRoute: typeof SiteIndexRoute
  SiteProjectsSlugRoute: typeof SiteProjectsSlugRoute
}

const SiteRouteChildren: SiteRouteChildren = {
  SiteContactRoute: SiteContactRoute,
  SiteResumeRoute: SiteResumeRoute,
  SiteWorkRoute: SiteWorkRoute,
  SiteIndexRoute: SiteIndexRoute,
  SiteProjectsSlugRoute: SiteProjectsSlugRoute,
}

const SiteRouteWithChildren = SiteRoute._addFileChildren(SiteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  SiteRoute: SiteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
